url: "https://etacticsgroup.github.io/jekyll-ata/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
sass:
    sass_dir: _sass
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true